name: CI

on: [workflow_dispatch, pull_request]

env:
  BINARY_PREFIX: "baidupcs-go_"
  BINARY_SUFFIX: ""
  PR_PROMPT: "::warning:: Build artifact will not be uploaded due to the workflow is trigged by pull request."
  LD_FLAGS: "-w -s"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v1

      - name: Lint Go Code
        run: |
          go get github.com/GeertJohan/go.rice
          go get github.com/GeertJohan/go.rice/rice
          #export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          
  build:
    name: Build binary CI
    runs-on: ubuntu-latest 
    needs: [lint]
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64 
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude: 
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: arm64
      fail-fast: true

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.14
    
    - name: Build binary file
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        IS_PR: ${{ !!github.head_ref }}
      run: |
        if [ $GOOS = "windows" ]; then export BINARY_SUFFIX="$BINARY_SUFFIX.exe"; fi
        if $IS_PR ; then echo $PR_PROMPT; fi
        export BINARY_NAME="$BINARY_PREFIX$GOOS_$GOARCH$BINARY_SUFFIX"
        go build -o "output/$BINARY_NAME" -ldflags "$LD_FLAGS" .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: ${{ !github.head_ref }}
      with:
        name: ${{ matrix.goos }}_${{ matrix.goarch }}
        path: output/
    
    
